[kh1]
scripts = [{ path = "scripts/kh1/", relative = true }]
base = 0x3A0606
thread_struct = 0x22B7280
exe = "KINGDOM HEARTS FINAL MIX.exe"
game_docs = "KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[kh2]
scripts = [{ path = "scripts/kh2/", relative = true }]
base = 0x56454E
thread_struct = 0x89E9A0
exe = "KINGDOM HEARTS II FINAL MIX.exe"
game_docs = "KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[bbs]
scripts = [{ path = "scripts/bbs/", relative = true }]
base = 0x60E334
thread_struct = 0x110B5970
exe = "KINGDOM HEARTS Birth by Sleep FINAL MIX.exe"
game_docs = "KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[recom]
scripts = [{ path = "scripts/recom/", relative = true }]
base = 0x4E4660
thread_struct = 0xBF7A80
exe = "KINGDOM HEARTS Re_Chain of Memories.exe"
game_docs = "KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[kh3d]
scripts = [{ path = "scripts/kh3d/", relative = true }]
base = 0x770E4A
thread_struct = 0x14DA6F20
exe = "KINGDOM HEARTS Dream Drop Distance.exe"
game_docs = "KINGDOM HEARTS HD 2.8 Final Chapter Prologue"
